language: ruby
rvm:
  - "2.4.1"
env:
  - DB=postgresql
before_install:
  - gem update --system
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database mydb_test' -U postgres
